name: Build

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ["x86", "x64"]
    env:
      Configuration: Release
      Platform: ${{ matrix.platform }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Locate MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          # As usual, obtained from: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json
          dotnet-version: "3.1.409" # since we now use this
      - name: Clear Nuget Cache
        run: dotnet nuget locals all --clear
      - name: Restore
        run: msbuild -t:Restore -m
      - name: Build
        run: msbuild -t:Build -m
      - name: Upload net472
        uses: actions/upload-artifact@v2
        with:
          name: BSIPA-net472-${{ env.Platform }}
          path: BSIPA-Meta/bin/${{ env.Platform }}/${{ env.Configuration }}/net472/
